# Generated by Django 5.1.7 on 2025-04-03 20:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_profile_capture_inactivity_timeout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.CharField(default=uuid.uuid4, max_length=255, unique=True, verbose_name='ID da Operação')),
                ('operation_type', models.CharField(choices=[('comparison', 'COMPARISON'), ('training', 'TRAINING'), ('generic', 'GENERIC')], max_length=50, verbose_name='Tipo de Operação')),
                ('status', models.CharField(choices=[('not_started', 'NOT_STARTED'), ('pending', 'PENDING'), ('in_progress', 'IN_PROGRESS'), ('processing', 'PROCESSING'), ('waiting', 'WAITING'), ('paused', 'PAUSED'), ('completed', 'COMPLETED'), ('failed', 'FAILED'), ('expired', 'EXPIRED'), ('cancelled', 'CANCELLED'), ('timeout', 'TIMEOUT')], default='not_started', max_length=20, verbose_name='Status')),
                ('progress', models.FloatField(default=0.0, verbose_name='Progresso')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='Resultado')),
                ('error', models.JSONField(blank=True, null=True, verbose_name='Erro')),
                ('meta', models.JSONField(blank=True, null=True, verbose_name='Metadados')),
                ('expiration', models.DateTimeField(blank=True, null=True, verbose_name='Expiração')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('user_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='accounts.usertoken', verbose_name='Token')),
            ],
            options={
                'verbose_name': 'Operação',
                'verbose_name_plural': 'Operações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AsyncTaskRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True, verbose_name='ID da Tarefa')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('processing', 'Processing'), ('waiting', 'Waiting'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('timeout', 'Timeout')], default='pending', max_length=20, verbose_name='Status')),
                ('input_data', models.JSONField(blank=True, null=True, verbose_name='Dados de Entrada')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='Resultado')),
                ('error', models.TextField(blank=True, null=True, verbose_name='Erro')),
                ('progress', models.FloatField(default=0.0, verbose_name='Progresso (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='async_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('user_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='async_tasks', to='accounts.usertoken', verbose_name='Token')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='async_tasks', to='core.operation', verbose_name='Operação')),
            ],
            options={
                'verbose_name': 'Tarefa Assíncrona',
                'verbose_name_plural': 'Tarefas Assíncronas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['operation_id'], name='core_operat_operati_4011c8_idx'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['operation_type'], name='core_operat_operati_ba6e5e_idx'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['user'], name='core_operat_user_id_11183b_idx'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['status'], name='core_operat_status_06ce49_idx'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['-created_at'], name='core_operat_created_c3e4b8_idx'),
        ),
        migrations.AddIndex(
            model_name='asynctaskrecord',
            index=models.Index(fields=['task_id'], name='core_asynct_task_id_ebaedc_idx'),
        ),
        migrations.AddIndex(
            model_name='asynctaskrecord',
            index=models.Index(fields=['status'], name='core_asynct_status_a8686f_idx'),
        ),
        migrations.AddIndex(
            model_name='asynctaskrecord',
            index=models.Index(fields=['user'], name='core_asynct_user_id_d3b65f_idx'),
        ),
        migrations.AddIndex(
            model_name='asynctaskrecord',
            index=models.Index(fields=['-created_at'], name='core_asynct_created_6d1153_idx'),
        ),
    ]
