# Generated by Django 5.1.7 on 2025-04-04 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='asynctaskrecord',
            name='core_asynct_user_id_d3b65f_idx',
        ),
        migrations.RemoveIndex(
            model_name='operation',
            name='core_operat_user_id_11183b_idx',
        ),
        migrations.RemoveIndex(
            model_name='operation',
            name='core_operat_status_06ce49_idx',
        ),
        migrations.RemoveField(
            model_name='asynctaskrecord',
            name='user',
        ),
        migrations.RemoveField(
            model_name='asynctaskrecord',
            name='user_token',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='error',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='result',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='status',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='user',
        ),
    ]
