# Generated by Django 5.1.7 on 2025-04-03 20:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_profile_capture_inactivity_timeout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text='URL da requisição', max_length=255, verbose_name='Caminho')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], help_text='Método HTTP', max_length=10, verbose_name='Método')),
                ('request_body', models.TextField(blank=True, null=True, verbose_name='Corpo da Requisição')),
                ('response_body', models.TextField(blank=True, null=True, verbose_name='Corpo da Resposta')),
                ('status_code', models.IntegerField(help_text='Código de status HTTP', validators=[django.core.validators.MinValueValidator(100)], verbose_name='Status')),
                ('execution_time', models.FloatField(help_text='Tempo de execução em segundos', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Tempo')),
                ('requester_ip', models.GenericIPAddressField(blank=True, help_text='Endereço IP do requisitante', null=True, verbose_name='IP')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Momento do registro', verbose_name='Data/Hora')),
                ('user', models.ForeignKey(blank=True, help_text='Usuário que fez a requisição', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('user_token', models.ForeignKey(blank=True, help_text='Token usado na requisição', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.usertoken', verbose_name='Token')),
            ],
            options={
                'verbose_name': 'Log de API',
                'verbose_name_plural': 'Logs de API',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='api_apilog_timesta_882ae6_idx'), models.Index(fields=['user_token'], name='api_apilog_user_to_99d22e_idx'), models.Index(fields=['status_code'], name='api_apilog_status__696b01_idx'), models.Index(fields=['method'], name='api_apilog_method_3f30aa_idx'), models.Index(fields=['path'], name='api_apilog_path_79d291_idx')],
            },
        ),
    ]
