# Generated by Django 5.1.7 on 2025-03-13 18:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_capture_inactivity_timeout'),
        ('api', '0002_apilog_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apilog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Log de API', 'verbose_name_plural': 'Logs de API'},
        ),
        migrations.AddField(
            model_name='apilog',
            name='request_body',
            field=models.TextField(blank=True, null=True, verbose_name='Corpo da Requisição'),
        ),
        migrations.AddField(
            model_name='apilog',
            name='requester_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Endereço IP do requisitante', null=True, verbose_name='IP'),
        ),
        migrations.AddField(
            model_name='apilog',
            name='response_body',
            field=models.TextField(blank=True, null=True, verbose_name='Corpo da Resposta'),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='execution_time',
            field=models.FloatField(help_text='Tempo de execução em segundos', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Tempo'),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], help_text='Método HTTP', max_length=10, verbose_name='Método'),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='path',
            field=models.CharField(help_text='URL da requisição', max_length=255, verbose_name='Caminho'),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='status_code',
            field=models.IntegerField(help_text='Código de status HTTP', validators=[django.core.validators.MinValueValidator(100)], verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='Momento do registro', verbose_name='Data/Hora'),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Usuário que fez a requisição', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='user_token',
            field=models.ForeignKey(blank=True, help_text='Token usado na requisição', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.usertoken', verbose_name='Token'),
        ),
        migrations.AddIndex(
            model_name='apilog',
            index=models.Index(fields=['-timestamp'], name='api_apilog_timesta_882ae6_idx'),
        ),
        migrations.AddIndex(
            model_name='apilog',
            index=models.Index(fields=['user'], name='api_apilog_user_id_ae730d_idx'),
        ),
        migrations.AddIndex(
            model_name='apilog',
            index=models.Index(fields=['method'], name='api_apilog_method_3f30aa_idx'),
        ),
        migrations.AddIndex(
            model_name='apilog',
            index=models.Index(fields=['status_code'], name='api_apilog_status__696b01_idx'),
        ),
    ]
