# Generated by Django 5.1.7 on 2025-03-25 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_capture_inactivity_timeout'),
        ('api', '0003_alter_apilog_options_apilog_request_body_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsyncTaskRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True, verbose_name='ID da Tarefa')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Em Processamento'), ('completed', 'Concluída'), ('failed', 'Falha'), ('expired', 'Expirada')], default='pending', max_length=20, verbose_name='Status')),
                ('input_data', models.JSONField(blank=True, null=True, verbose_name='Dados de Entrada')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='Resultado')),
                ('error', models.TextField(blank=True, null=True, verbose_name='Erro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='async_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('user_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='async_tasks', to='accounts.usertoken', verbose_name='Token')),
            ],
            options={
                'verbose_name': 'Tarefa Assíncrona',
                'verbose_name_plural': 'Tarefas Assíncronas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task_id'], name='api_asyncta_task_id_45da84_idx'), models.Index(fields=['status'], name='api_asyncta_status_9b4379_idx'), models.Index(fields=['user'], name='api_asyncta_user_id_e7b8b5_idx')],
            },
        ),
    ]
