# Generated by Django 5.1.7 on 2025-03-25 17:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_capture_inactivity_timeout'),
        ('api', '0004_asynctaskrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='apilog',
            name='api_apilog_user_id_ae730d_idx',
        ),
        migrations.AddIndex(
            model_name='apilog',
            index=models.Index(fields=['user_token'], name='api_apilog_user_to_99d22e_idx'),
        ),
        migrations.AddIndex(
            model_name='apilog',
            index=models.Index(fields=['path'], name='api_apilog_path_79d291_idx'),
        ),
        migrations.AddIndex(
            model_name='asynctaskrecord',
            index=models.Index(fields=['-created_at'], name='api_asyncta_created_21acb2_idx'),
        ),
    ]
