# Generated by Django 4.2.7 on 2024-09-25 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_client_class', models.CharField(max_length=255)),
                ('configurations', models.JSONField(default=dict)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='accounts.usertoken')),
            ],
            options={
                'unique_together': {('token', 'api_client_class')},
            },
        ),
    ]
