# Generated by Django 4.2.7 on 2024-10-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIClientConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_client_class', models.CharField(max_length=255, unique=True)),
                ('api_key', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=255)),
                ('configurations', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.RemoveField(
            model_name='tokenconfiguration',
            name='api_key',
        ),
    ]
