# Generated by Django 4.2.7 on 2025-02-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='capture_inactivity_timeout',
            field=models.IntegerField(default=10, verbose_name='Tempo de Inatividade de Captura (minutos)'),
        ),
    ]
