# Generated by Django 4.2.7 on 2024-10-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tokenconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenconfiguration',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tokenconfiguration',
            name='model_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tokenconfiguration',
            name='configurations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
