# Generated by Django 4.2.7 on 2025-02-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_capture_inactivity_timeout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='capture_inactivity_timeout',
            field=models.IntegerField(default=5, verbose_name='Tempo de Inatividade de Captura (minutos)'),
        ),
    ]
