# Generated by Django 4.2.7 on 2024-10-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_aiclientconfiguration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('processor_id', models.CharField(max_length=100)),
                ('credentials', models.FileField(blank=True, null=True, upload_to='documentai_credentials/')),
            ],
        ),
        migrations.AddField(
            model_name='aiclientconfiguration',
            name='base_instruction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiclientconfiguration',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiclientconfiguration',
            name='responses',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tokenconfiguration',
            name='base_instruction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tokenconfiguration',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tokenconfiguration',
            name='responses',
            field=models.TextField(blank=True, null=True),
        ),
    ]
