# Generated by Django 4.2.7 on 2024-10-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_documentaiconfiguration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_instruction', models.TextField(blank=True, help_text='Instrução base padrão para todas as IAs.', null=True)),
                ('prompt', models.TextField(blank=True, help_text='Prompt padrão para todas as IAs.', null=True)),
                ('responses', models.TextField(blank=True, help_text='Respostas padrão para todas as IAs.', null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='aiclientconfiguration',
            name='base_instruction',
        ),
        migrations.RemoveField(
            model_name='aiclientconfiguration',
            name='prompt',
        ),
        migrations.RemoveField(
            model_name='aiclientconfiguration',
            name='responses',
        ),
        migrations.RemoveField(
            model_name='documentaiconfiguration',
            name='credentials',
        ),
        migrations.AlterField(
            model_name='tokenconfiguration',
            name='base_instruction',
            field=models.TextField(blank=True, help_text='Instrução base personalizada para este token. Deixe vazio para usar a configuração global.', null=True),
        ),
        migrations.AlterField(
            model_name='tokenconfiguration',
            name='prompt',
            field=models.TextField(blank=True, help_text='Prompt personalizado para este token. Deixe vazio para usar a configuração global.', null=True),
        ),
        migrations.AlterField(
            model_name='tokenconfiguration',
            name='responses',
            field=models.TextField(blank=True, help_text='Respostas personalizadas para este token. Deixe vazio para usar a configuração global.', null=True),
        ),
    ]
