# Generated by Django 4.2.7 on 2024-10-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_tokenconfiguration_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenconfiguration',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
