# Generated by Django 4.2.7 on 2024-10-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_globalconfiguration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='base_instruction',
            field=models.TextField(blank=True, help_text='Instrução base personalizada para este token. Deixe vazio para usar a configuração global.', null=True),
        ),
        migrations.AddField(
            model_name='usertoken',
            name='prompt',
            field=models.TextField(blank=True, help_text='Prompt personalizado para este token. Deixe vazio para usar a configuração global.', null=True),
        ),
        migrations.AddField(
            model_name='usertoken',
            name='responses',
            field=models.TextField(blank=True, help_text='Respostas personalizadas para este token. Deixe vazio para usar a configuração global.', null=True),
        ),
    ]
