# Generated by Django 4.2.7 on 2024-10-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_tokenconfiguration_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenconfiguration',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
