# Generated by Django 4.2.7 on 2024-10-22 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_usertoken_base_instruction_usertoken_prompt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokenconfiguration',
            name='base_instruction',
        ),
        migrations.RemoveField(
            model_name='tokenconfiguration',
            name='prompt',
        ),
        migrations.RemoveField(
            model_name='tokenconfiguration',
            name='responses',
        ),
    ]
