# Generated by Django 4.2.7 on 2024-11-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_tokenconfiguration_base_instruction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='training_file',
            field=models.FileField(blank=True, help_text='Arquivo de treinamento para este token.', null=True, upload_to='training_files/'),
        ),
    ]
