# Generated by Django 4.2.7 on 2024-11-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_usertoken_training_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfiguration',
            name='training_file',
            field=models.FileField(blank=True, help_text='Arquivo de treinamento global para todas as IAs.', null=True, upload_to='global_training_files/'),
        ),
    ]
