# Generated by Django 5.1.7 on 2025-03-25 17:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Nome do produto ou cliente', max_length=100)),
                ('version', models.CharField(help_text='Número da versão (ex: 1.0.0)', max_length=50)),
                ('release_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('download_url', models.URLField(help_text='URL para download do cliente', max_length=500)),
                ('is_mandatory', models.BooleanField(default=False, help_text='Se a atualização é obrigatória')),
                ('release_notes', models.TextField(blank=True, help_text='Notas de lançamento desta versão')),
                ('active', models.BooleanField(default=True, help_text='Se esta versão está ativa')),
            ],
            options={
                'verbose_name': 'Versão do Cliente',
                'verbose_name_plural': 'Versões dos Clientes',
                'ordering': ['-release_date'],
            },
        ),
    ]
