# Generated by Django 4.2.7 on 2024-11-16 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_client_class', models.CharField(max_length=255, unique=True)),
                ('api_key', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Global - Cliente de IA',
                'verbose_name_plural': 'Global - Clientes de IA',
            },
        ),
        migrations.CreateModel(
            name='AIClientConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('model_name', models.CharField(blank=True, max_length=255, null=True)),
                ('configurations', models.JSONField(blank=True, default=dict)),
                ('ai_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_config.aiclient')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='accounts.usertoken')),
            ],
            options={
                'verbose_name': 'Token - Configuração de Cliente de IA',
                'verbose_name_plural': 'Token - Configurações de Cliente de IA',
                'unique_together': {('token', 'ai_client')},
            },
        ),
        migrations.CreateModel(
            name='AITrainingFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='training_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Arquivo de Treinamento',
                'verbose_name_plural': 'Arquivos de Treinamento',
            },
        ),
        migrations.CreateModel(
            name='DocumentAIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('processor_id', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Configuração de Processamento de Documento',
                'verbose_name_plural': 'Configurações de Processamento de Documento',
            },
        ),
        migrations.CreateModel(
            name='TokenAIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_instruction', models.TextField(blank=True, help_text='Instrução base personalizada para este token.', null=True)),
                ('prompt', models.TextField(blank=True, help_text='Prompt personalizado para este token.', null=True)),
                ('responses', models.TextField(blank=True, help_text='Respostas personalizadas para este token.', null=True)),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_configuration', to='accounts.usertoken')),
            ],
            options={
                'verbose_name': 'Token - Configuração de Prompt',
                'verbose_name_plural': 'Token - Configurações de Prompt',
            },
        ),
        migrations.CreateModel(
            name='AIClientTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_parameters', models.JSONField(blank=True, default=dict, help_text='Parâmetros de treinamento para esta configuração de cliente de IA.')),
                ('trained_model_name', models.CharField(blank=True, editable=False, help_text='Nome do modelo treinado. Não é editável pelo administrador.', max_length=255, null=True)),
                ('ai_client_configuration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='training', to='ai_config.aiclientconfiguration')),
            ],
            options={
                'verbose_name': 'Token - Parâmetros de Treinamento de IA',
                'verbose_name_plural': 'Token - Parâmetros de Treinamento de IA',
            },
        ),
    ]
