# Generated by Django 4.2.7 on 2025-02-07 14:09

import ai_config.storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIClientConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da IA (personalizado)')),
                ('enabled', models.BooleanField(default=False)),
                ('model_name', models.CharField(blank=True, max_length=255, null=True)),
                ('configurations', models.JSONField(blank=True, default=dict)),
                ('use_system_message', models.BooleanField(default=False, help_text='Indica se deve utilizar a mensagem do sistema, se suportado pela API.', verbose_name='Usar System Message')),
            ],
            options={
                'verbose_name': 'Token - Configuração de Cliente de IA',
                'verbose_name_plural': 'Token - Configurações de Cliente de IA',
            },
        ),
        migrations.CreateModel(
            name='AIClientGlobalConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('api_client_class', models.CharField(max_length=255)),
                ('api_url', models.URLField(blank=True, null=True)),
                ('api_key', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Global - Cliente de IA',
                'verbose_name_plural': 'Global - Clientes de IA',
            },
        ),
        migrations.CreateModel(
            name='AITrainingFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(storage=ai_config.storage.OverwriteStorage(), upload_to='training_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Arquivo de Treinamento',
                'verbose_name_plural': 'Arquivos de Treinamento',
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DoclingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('do_ocr', models.BooleanField(default=False, verbose_name='Executar OCR')),
                ('do_table_structure', models.BooleanField(default=False, verbose_name='Extrair Estrutura de Tabela')),
                ('do_cell_matching', models.BooleanField(default=False, verbose_name='Ativar Correspondência de Células')),
                ('accelerator_device', models.CharField(choices=[('auto', 'Auto'), ('cpu', 'CPU'), ('cuda', 'CUDA'), ('mps', 'MPS')], default='auto', max_length=10, verbose_name='Dispositivo de Aceleração')),
                ('custom_options', models.JSONField(blank=True, help_text="Insira opções adicionais em formato JSON (por exemplo, {'images_scale': 1.2}).", null=True, verbose_name='Opções Customizadas')),
            ],
            options={
                'verbose_name': 'Configuração Docling',
                'verbose_name_plural': 'Configurações Docling',
            },
        ),
        migrations.CreateModel(
            name='DocumentAIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('processor_id', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Configuração de Processamento de Documento',
                'verbose_name_plural': 'Configurações de Processamento de Documento',
            },
        ),
        migrations.CreateModel(
            name='TokenAIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_instruction', models.TextField(blank=True, help_text='Instrução base personalizada para este token.', null=True)),
                ('prompt', models.TextField(blank=True, help_text='Prompt personalizado para este token.', null=True)),
                ('responses', models.TextField(blank=True, help_text='Respostas personalizadas para este token.', null=True)),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_configuration', to='accounts.usertoken')),
                ('training_file', models.ForeignKey(blank=True, help_text='Selecione o arquivo de treinamento para este token.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_config.aitrainingfile')),
            ],
            options={
                'verbose_name': 'Token - Configuração de Prompt',
                'verbose_name_plural': 'Token - Configurações de Prompt',
            },
        ),
        migrations.CreateModel(
            name='AIClientTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_parameters', models.JSONField(blank=True, default=dict, help_text='Parâmetros de treinamento para esta configuração de cliente de IA.')),
                ('trained_model_name', models.CharField(blank=True, editable=False, help_text='Nome do modelo treinado. Não é editável pelo administrador.', max_length=255, null=True)),
                ('ai_client_configuration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='training', to='ai_config.aiclientconfiguration')),
            ],
            options={
                'verbose_name': 'Token - Parâmetros de Treinamento de IA',
                'verbose_name_plural': 'Token - Parâmetros de Treinamento de IA',
            },
        ),
        migrations.AddField(
            model_name='aiclientconfiguration',
            name='ai_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_config.aiclientglobalconfiguration'),
        ),
        migrations.AddField(
            model_name='aiclientconfiguration',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='accounts.usertoken'),
        ),
        migrations.CreateModel(
            name='TrainingCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('temp_file', models.FileField(blank=True, null=True, upload_to='training_captures/')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('ai_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_config.aiclientglobalconfiguration')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_captures', to='accounts.usertoken')),
            ],
            options={
                'verbose_name': 'Captura de Treinamento',
                'verbose_name_plural': 'Capturas de Treinamento',
                'unique_together': {('token', 'ai_client')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='aiclientconfiguration',
            unique_together={('token', 'name')},
        ),
    ]
