# Generated by Django 4.2.7 on 2025-02-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiclientglobalconfiguration',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='aiclientglobalconfiguration',
            unique_together={('name', 'api_client_class')},
        ),
    ]
