# Generated by Django 4.2.7 on 2025-02-12 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_config', '0002_alter_aiclientglobalconfiguration_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentAIConfiguration',
        ),
    ]
