# Generated by Django 4.2.7 on 2024-11-18 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_config', '0002_aitrainingfile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenaiconfiguration',
            name='training_file',
            field=models.ForeignKey(blank=True, help_text='Selecione o arquivo de treinamento para este token.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_config.aitrainingfile'),
        ),
    ]
