# Generated by Django 4.2.7 on 2025-02-14 00:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ai_config', '0003_delete_documentaiconfiguration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokenaiconfiguration',
            name='training_file',
        ),
        migrations.AlterField(
            model_name='tokenaiconfiguration',
            name='prompt',
            field=models.TextField(default=django.utils.timezone.now, help_text='Prompt específico para cada comparação (obrigatório).'),
            preserve_default=False,
        ),
    ]
