# Generated by Django 4.2.7 on 2024-11-18 19:02

import ai_config.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_config', '0003_tokenaiconfiguration_training_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aitrainingfile',
            name='file',
            field=models.FileField(storage=ai_config.storage.OverwriteStorage(), upload_to='training_files/'),
        ),
    ]
