# Generated by Django 4.2.7 on 2024-11-18 19:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_config', '0004_alter_aitrainingfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitrainingfile',
            name='name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='aitrainingfile',
            unique_together={('user', 'name')},
        ),
    ]
