# Generated by Django 4.2.7 on 2025-02-17 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('ai_config', '0004_remove_tokenaiconfiguration_training_file_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trainingcapture',
            unique_together={('token',)},
        ),
        migrations.AddField(
            model_name='trainingcapture',
            name='ai_client_config',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ai_config.aiclientconfiguration'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='trainingcapture',
            name='ai_client',
        ),
    ]
