# Generated by Django 4.2.7 on 2025-02-18 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('ai_config', '0005_alter_trainingcapture_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trainingcapture',
            unique_together={('token', 'ai_client_config')},
        ),
    ]
