# Generated by Django 4.2.7 on 2024-11-19 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('ai_config', '0005_aitrainingfile_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('ai_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_config.aiclient')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_captures', to='accounts.usertoken')),
            ],
            options={
                'verbose_name': 'Captura de Treinamento',
                'verbose_name_plural': 'Capturas de Treinamento',
                'unique_together': {('token', 'ai_client')},
            },
        ),
    ]
