# Generated by Django 4.2.7 on 2024-11-19 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_config', '0006_trainingcapture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AIClient',
            new_name='AIClientGlobalConfiguration',
        ),
    ]
