# Generated by Django 4.2.7 on 2025-02-18 11:29

import ai_config.models
import ai_config.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('ai_config', '0006_alter_trainingcapture_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trainingcapture',
            unique_together={('token',)},
        ),
        migrations.AlterField(
            model_name='trainingcapture',
            name='temp_file',
            field=models.FileField(blank=True, null=True, storage=ai_config.storage.OverwriteStorage(), upload_to=ai_config.models.TrainingCapture._generate_temp_filename),
        ),
    ]
