# Generated by Django 4.2.7 on 2024-11-19 17:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ai_config', '0007_rename_aiclient_aiclientglobalconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcapture',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingcapture',
            name='temp_file',
            field=models.FileField(blank=True, null=True, upload_to='training_captures/'),
        ),
    ]
