# Generated by Django 4.2.7 on 2025-02-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_config', '0007_alter_trainingcapture_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenaiconfiguration',
            name='responses',
            field=models.TextField(default=0, help_text='Respostas personalizadas para este token.'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AIClientTraining',
        ),
    ]
