# Generated by Django 4.2.7 on 2025-02-23 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_config', '0008_alter_tokenaiconfiguration_responses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AITraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=255)),
                ('status', models.CharField(default='not_started', max_length=20)),
                ('progress', models.FloatField(default=0)),
                ('model_name', models.CharField(blank=True, max_length=255, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_config.aiclientconfiguration')),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_config.aitrainingfile')),
            ],
            options={
                'verbose_name': 'Treinamento de IA',
                'verbose_name_plural': 'Treinamentos de IA',
            },
        ),
    ]
