# Generated by Django 4.2.7 on 2024-11-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_config', '0008_trainingcapture_create_at_trainingcapture_temp_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcapture',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
