# Generated by Django 4.2.7 on 2025-02-23 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_config', '0009_aitraining'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aitraining',
            name='progress',
        ),
    ]
