# Generated by Django 4.2.7 on 2025-01-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_config', '0009_trainingcapture_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiclientglobalconfiguration',
            name='api_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiclientglobalconfiguration',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aiclientglobalconfiguration',
            name='api_client_class',
            field=models.CharField(max_length=255),
        ),
    ]
