# Generated by Django 4.2.7 on 2025-02-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_config', '0010_remove_aitraining_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aitraining',
            name='status',
            field=models.CharField(choices=[('not_started', 'Não Iniciado'), ('in_progress', 'Em Andamento'), ('completed', 'Concluído'), ('failed', 'Falhou')], default='not_started', max_length=20),
        ),
    ]
