# Generated by Django 4.2.7 on 2025-01-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_config', '0010_aiclientglobalconfiguration_api_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiclientglobalconfiguration',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
