# Generated by Django 4.2.7 on 2025-01-30 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('ai_config', '0011_alter_aiclientglobalconfiguration_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aiclientconfiguration',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='aiclientconfiguration',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='Nome da IA (personalizado)'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='aiclientconfiguration',
            unique_together={('token', 'name')},
        ),
    ]
