# Generated by Django 4.2.7 on 2025-02-24 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_config', '0011_alter_aitraining_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AITrainedModelsManager',
            fields=[
            ],
            options={
                'verbose_name': 'Gerenciador de Modelos Treinados',
                'verbose_name_plural': 'Gerenciador de Modelos Treinados',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ai_config.aiclientglobalconfiguration',),
        ),
        migrations.CreateModel(
            name='AITrainingFilesManager',
            fields=[
            ],
            options={
                'verbose_name': 'Gerenciador de Arquivos de Treinamento',
                'verbose_name_plural': 'Gerenciador de Arquivos de Treinamento',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ai_config.aiclientglobalconfiguration',),
        ),
    ]
