# Generated by Django 4.2.7 on 2025-02-25 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_config', '0012_aitrainedmodelsmanager_aitrainingfilesmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitraining',
            name='progress',
            field=models.FloatField(default=0),
        ),
    ]
