# Generated by Django 4.2.7 on 2025-02-03 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_config', '0012_alter_aiclientconfiguration_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoclingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('do_ocr', models.BooleanField(default=False, verbose_name='Executar OCR')),
                ('do_table_structure', models.BooleanField(default=False, verbose_name='Extrair Estrutura de Tabela')),
                ('do_cell_matching', models.BooleanField(default=False, verbose_name='Ativar Correspondência de Células')),
                ('accelerator_device', models.CharField(choices=[('cpu', 'CPU'), ('gpu', 'GPU')], default='cpu', max_length=10, verbose_name='Dispositivo de Aceleração')),
                ('use_fp16', models.BooleanField(default=False, verbose_name='Utilizar FP16')),
                ('custom_options', models.JSONField(blank=True, help_text='Opcional: insira opções adicionais em formato JSON.', null=True, verbose_name='Opções Customizadas')),
            ],
            options={
                'verbose_name': 'Configuração Docling',
                'verbose_name_plural': 'Configurações Docling',
            },
        ),
    ]
