# Generated by Django 4.2.7 on 2025-02-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_config', '0013_aitraining_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aitraining',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='aiclientconfiguration',
            name='training_configurations',
            field=models.JSONField(blank=True, default=dict, help_text='Configurações específicas para treinamento da IA'),
        ),
        migrations.AddField(
            model_name='aitraining',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
