# Generated by Django 4.2.7 on 2025-02-03 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_config', '0013_doclingconfiguration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doclingconfiguration',
            name='use_fp16',
        ),
    ]
