# Generated by Django 4.2.7 on 2025-02-25 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_capture_inactivity_timeout'),
        ('ai_config', '0014_remove_aitraining_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiclientconfiguration',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='aiclientconfiguration',
            name='training_configurations',
        ),
        migrations.RemoveField(
            model_name='aitraining',
            name='finished_at',
        ),
        migrations.AddField(
            model_name='aitraining',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='AIClientTokenConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_config.aiclientconfiguration')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.usertoken')),
            ],
            options={
                'verbose_name': 'Token - IA Habilitada',
                'verbose_name_plural': 'Token - IAs Habilitadas',
                'unique_together': {('token', 'ai_config')},
            },
        ),
        migrations.AddField(
            model_name='aiclientconfiguration',
            name='tokens',
            field=models.ManyToManyField(related_name='ai_clients', through='ai_config.AIClientTokenConfig', to='accounts.usertoken', verbose_name='Tokens associados'),
        ),
    ]
