# Generated by Django 4.2.7 on 2025-02-03 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_config', '0014_remove_doclingconfiguration_use_fp16'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doclingconfiguration',
            name='accelerator_device',
            field=models.CharField(choices=[('auto', 'Auto'), ('cpu', 'CPU'), ('cuda', 'CUDA'), ('mps', 'MPS')], default='auto', max_length=10, verbose_name='Dispositivo de Aceleração'),
        ),
        migrations.AlterField(
            model_name='doclingconfiguration',
            name='custom_options',
            field=models.JSONField(blank=True, help_text="Insira opções adicionais em formato JSON (por exemplo, {'images_scale': 1.2}).", null=True, verbose_name='Opções Customizadas'),
        ),
    ]
