# Generated by Django 4.2.7 on 2025-02-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_config', '0015_remove_aiclientconfiguration_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiclientconfiguration',
            name='training_configurations',
            field=models.JSONField(blank=True, default=dict, help_text='Configurações específicas para treinamento no formato chave=valor', verbose_name='Configurações de Treinamento'),
        ),
    ]
