# Generated by Django 4.2.7 on 2025-02-25 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_config', '0016_aiclientconfiguration_training_configurations'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aiclientconfiguration',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='aiclientconfiguration',
            name='token',
        ),
    ]
