# Generated by Django 4.2.7 on 2025-02-25 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_config', '0017_alter_aiclientconfiguration_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiclientconfiguration',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ai_configurations', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='aiclientconfiguration',
            unique_together={('user', 'name')},
        ),
    ]
