# Generated by Django 4.2.7 on 2025-02-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_config', '0018_aiclientconfiguration_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiclientconfiguration',
            name='configurations',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='aiclientconfiguration',
            name='training_configurations',
            field=models.JSONField(blank=True, default=dict, help_text='Configurações específicas para treinamento no formato chave=valor', null=True, verbose_name='Configurações de Treinamento'),
        ),
    ]
