# Generated by Django 5.1.7 on 2025-03-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_config', '0019_alter_aiclientconfiguration_configurations_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aitrainingfilesmanager',
            options={'verbose_name': 'Arquivos de Treinamento na IA', 'verbose_name_plural': 'Arquivos de Treinamento na IA'},
        ),
        migrations.AlterModelOptions(
            name='tokenaiconfiguration',
            options={'verbose_name': 'Token - Configuração de IA', 'verbose_name_plural': 'Token - Configurações de IA'},
        ),
        migrations.AlterField(
            model_name='tokenaiconfiguration',
            name='responses',
            field=models.TextField(blank=True, help_text='Respostas personalizadas para este token.', null=True),
        ),
    ]
