# Generated by Django 5.1.7 on 2025-03-14 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_config', '0020_alter_aitrainingfilesmanager_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aitrainingfile',
            name='file',
        ),
        migrations.AddField(
            model_name='aitrainingfile',
            name='file_path',
            field=models.CharField(default=1, editable=False, max_length=255),
            preserve_default=False,
        ),
    ]
