# Generated by Django 5.1.7 on 2025-03-17 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_config', '0021_remove_aitrainingfile_file_aitrainingfile_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingcapture',
            name='temp_file',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
