# Generated by Django 5.1.7 on 2025-03-25 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_config', '0022_alter_trainingcapture_temp_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AITrainedModelsManager',
        ),
        migrations.DeleteModel(
            name='AITrainingFilesManager',
        ),
        migrations.CreateModel(
            name='AIFilesManager',
            fields=[
            ],
            options={
                'verbose_name': 'Arquivos na IA',
                'verbose_name_plural': 'Arquivos na IA',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ai_config.aiclientglobalconfiguration',),
        ),
        migrations.CreateModel(
            name='AIModelsManager',
            fields=[
            ],
            options={
                'verbose_name': 'Gerenciador de Modelos das IAs',
                'verbose_name_plural': 'Gerenciador de Modelos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ai_config.aiclientglobalconfiguration',),
        ),
    ]
