# Generated by Django 5.1.7 on 2025-03-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_config', '0023_delete_aitrainedmodelsmanager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aitraining',
            name='status',
            field=models.CharField(choices=[('not_started', 'Não Iniciado'), ('in_progress', 'Em Andamento'), ('completed', 'Concluído'), ('failed', 'Falhou'), ('cancelled', 'Cancelado')], default='not_started', max_length=20),
        ),
    ]
