# Generated by Django 5.1.7 on 2025-04-01 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_config', '0024_alter_aitraining_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aitraining',
            name='status',
            field=models.CharField(choices=[('not_started', 'NOT_STARTED'), ('pending', 'PENDING'), ('in_progress', 'IN_PROGRESS'), ('processing', 'PROCESSING'), ('waiting', 'WAITING'), ('paused', 'PAUSED'), ('completed', 'COMPLETED'), ('failed', 'FAILED'), ('expired', 'EXPIRED'), ('cancelled', 'CANCELLED'), ('timeout', 'TIMEOUT')], default='not_started', max_length=20),
        ),
    ]
